### ISSUE TITLE
top-level syntax

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/violet#31]
Current surface is almost the core term, for example, we can have `let x : a = t; u` directly. But in the top-level this setup is inconvenience, user will not want only single expression there in a file! Thus, the redesign is required, current plan is there will have three top-level form
1. `let x : a = t`
2. `postulate x : t`
3. inductive type (notice the `->` is not allowed till #29 done)
   ```
   data Nat
   | zero : Nat
   | suc : Nat -> Nat
   ```

and don't allow other forms in top-level!

### Tasks

- [ ] top-level let
- [ ] top-level postulate
- [ ] inductive type
- [ ] module information (with export list)
   ```
   module Core (Nat)
   ```

**Comment by rayshih** [comment]
Does the idea like following work?

```idris
data Raw
    = RSrcPos Position Raw
    | RVar Name               -- x
    | RLam Name Raw           -- λ x . t
    | RApp Raw Raw            -- t u
    | RU                      -- U
    | RPi Name RTy RTy        -- (x : a) → b
    | RTopLevel TopLevelRaw

data TopLevelRaw
    = RLet Name RTy Raw Raw   -- let x : a = t; u
    | RPostulate Name RTy Raw -- posulate x : a; u
    -- inductive type
    -- data Nat
    -- | zero : Nat
    -- | suc : Nat -> Nat
    -- ; u
    | RData Name (List (Name, RTy)) Raw

data ModuleInfoRaw = ....

data ModuleRaw = ModuleRaw ModuleInfoRaw TopLevelRaw
```

or you want to make it a more flattened structure?


```idris
data Raw
    = RSrcPos Position Raw
    | RVar Name               -- x
    | RLam Name Raw           -- λ x . t
    | RApp Raw Raw            -- t u
    | RU                      -- U
    | RPi Name RTy RTy        -- (x : a) → b
    | RTopLevel TopLevelRaw

data TopLevelRaw
    = RLet Name RTy Raw   -- let x : a = t
    | RPostulate Name RTy -- posulate x : a
    -- inductive type
    -- data Nat
    -- | zero : Nat
    -- | suc : Nat -> Nat
    | RData Name (List (Name, RTy))

data ModuleInfoRaw = ....

data ModuleRaw = ModuleRaw ModuleInfoRaw (List TopLevelRaw)
```

**Comment by dannypsnl** [comment]
The second one, and `Raw` will not need `RTopLevel`, it's lower expression. On the another hand, `Raw` need another `RLet Name RTy Raw Raw`, for `let x : a = t in u`

You can write `TLet` as following to avoid conflict I guess
```
data TopLevelRaw
    = TLet Name RTy Raw   -- let x : a = t
    | TPostulate Name RTy -- posulate x : a
    -- inductive type
    -- data Nat
    -- | zero : Nat
    -- | suc : Nat -> Nat
    | TData Name (List (Name, RTy))
```
