### ISSUE TITLE
separate compilation framework

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/violet#6]
Let some simple code(which means those mono-typed instances) work, and build an executable with parallel compilation support. A draft like below

```scm
; executable name, there has no module name stands for it
(app hello
  ; import hello module
  (import identity))

(println (string-+ "hello " (int->string (identity 491))))
```

### Tasks
- [x] config command-line interface, based on [command-line](https://docs.racket-lang.org/reference/Command-Line_Parsing.html#%28form._%28%28lib._racket%2Fcmdline..rkt%29._command-line%29%29) to build following commands
    - [x] `violet build <dir-path>`: find all files in the `dir-path`, compile all of them, and create executables if they are application files
    - [x] `violet compile <file-path>`: generates corresponding object file for given file
- [x] create a function that will start compiling a module file
- [x] use `place` or `future` to fork function out, returns an error or a complete notification back to the main routine
