### ISSUE TITLE
[concept] application file

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/violet#8]
The file format would like
```scm
(app <app-name>)
; expressions or definitions
```

Here is a simple example
```scm
(app hello)

(printf "hello\n")
```

### Tasks
- [x] separate application file, but only one entry for both kinds of file: app and module
- [x] once the compiler knows the mode, it will load different workflow
- [x] enable parse expression in app mode
- [ ] handle function apply syntax
    - [ ] type check
    - [x] codegen

**Comment by dannypsnl** [comment]
In fact, I think I should just move on to a new issue or just track type-checking in the source code. The main framework is already done in 64e11d468f3baf3d8f7db49d529244dfc73bee90
