### ISSUE TITLE
`type` keyword and its usage

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/violet#9]
Top-level definition `type`
```scm
; data type
(type nat
  zero
  (suc nat))

; type alias
(type byte = uint8)
```

### Tasks
- [ ] handle such type definition in the parser
- [ ] type checker can use these definitions
- [ ] generate runtime encoding for these types' instances

**Comment by dannypsnl** [comment]
drop, replaced with generalized data type
